exclude: "{{ cookiecutter.handler_slug }}_handler/"

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: "https://github.com/psf/black"
    rev: 23.7.0
    hooks:
      - id: black
  - repo: "https://github.com/PyCQA/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503"]
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--cache-dir=/dev/null", "--ignore-missing-imports"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
